### ISSUE TITLE
[debs] Calling ros2 without having sourced setup file gives traceback

### ISSUE THREAD

**Issue by dhood** [ros2/ros2cli#39]
With ros2 packages from debians, without having sourced the r2b2/setup.bash, the `ros2` console script is on the path but not the rest of `ros2cli`. So, if you haven't sourced the setup.bash, you get:

```
<new terminal>
root@87c44666d4d5:/# ros2 run demo_nodes_py talker_qos
Traceback (most recent call last):
  File "/usr/bin/ros2", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ros2cli==0.0.0' distribution was not found and is required by the application
root@87c44666d4d5:/# . /opt/ros/r2b2/setup.bash 
root@87c44666d4d5:/# ros2 run demo_nodes_py talker_qos
Best effort publisher
Publishing: "Hello World: 0"
Publishing: "Hello World: 1"
Publishing: "Hello World: 2"
```

I understand that the console script is auto-generated, but if there's a way around this it will improve user experience since I expect this to happen to people quite often.

**Comment by dhood** [comment]
OK, this looks like the user's perspective of https://github.com/ros2/rosdistro/issues/9. I'll close this in favour of that ticket.
