### ISSUE TITLE
ros2 topic pub: parsing arguments fails

### ISSUE THREAD

**Issue by hdino** [ros2/ros2cli#468]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - Binaries
- Version or commit hash:
  - 0.8.7-1bionic.20200218.185111
- DDS implementation:
  - Default
- Client library (if applicable):
  - python3-yaml, version: 3.12-1build2

#### Steps to reproduce issue
Execute the following command:
```
ros2 topic pub /test geometry_msgs/msg/Vector3 "{x:0, y:0, z:0}"
```
(According to [this ROS2 topic tutorial](https://index.ros.org/doc/ros2/Tutorials/Topics/Understanding-ROS2-Topics/))

#### Expected behavior
Messages as described should be published.

#### Actual behavior
The command fails with the following traceback:
```
Traceback (most recent call last):
  File "/opt/ros/eloquent/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.8.7', 'console_scripts', 'ros2')()
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2cli/cli.py", line 69, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/command/topic.py", line 43, in main
    return extension.main(args=args)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/verb/pub.py", line 76, in main
    return main(args)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/verb/pub.py", line 91, in main
    qos_profile)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/verb/pub.py", line 106, in publisher
    values_dictionary = yaml.safe_load(values)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 35, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 143, in parse_implicit_document_start
    StreamEndToken):
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 252, in fetch_more_tokens
    return self.fetch_plain()
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 676, in fetch_plain
    self.tokens.append(self.scan_plain())
  File "/usr/lib/python3/dist-packages/yaml/scanner.py", line 1299, in scan_plain
    "Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.")
yaml.scanner.ScannerError: while scanning a plain scalar
  in "<unicode string>", line 1, column 2:
    {x:0, y:0, z:0}
     ^
found unexpected ':'
  in "<unicode string>", line 1, column 3:
    {x:0, y:0, z:0}
      ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
```

**Comment by hdino** [comment]
## Solution
The command line must look like this:
```
ros2 topic pub /test geometry_msgs/msg/Vector3 "{x:0, y:0, z:0}"
```
