### ISSUE TITLE
import_message error when message/module is not found is not informative

### ISSUE THREAD

**Issue by heuristicus** [ros2/ros2cli#557]
I have been going through the tutorials and made a mistake in the [single package interface](https://index.ros.org/doc/ros2/Tutorials/Single-Package-Define-And-Use-Interface) where I built the `more_interfaces` package in one terminal but did not run `. install/setup.bash` in my other terminal to update the workspace.

Running the publisher for the message in the correctly set up terminal works, but when I try to echo the topic in the one where I forgot to source the workspace, I get

```
ros2 topic echo /address_book 
Traceback (most recent call last):
  File "/opt/ros/foxy/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.9.7', 'console_scripts', 'ros2')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/command/topic.py", line 41, in main
    return extension.main(args=args)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/verb/echo.py", line 81, in main
    return main(args)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/verb/echo.py", line 95, in main
    message_type = get_msg_class(node, args.topic_name, include_hidden_topics=True)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/api/__init__.py", line 88, in get_msg_class
    msg_class = _get_msg_class(node, topic, include_hidden_topics)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ros2topic/api/__init__.py", line 133, in _get_msg_class
    return get_message(message_type)
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_runtime_py/utilities.py", line 28, in get_message
    interface = import_message_from_namespaced_type(get_message_namespaced_type(identifier))
  File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_runtime_py/import_message.py", line 30, in import_message_from_namespaced_type
    module = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'more_interfaces'
```

The crash is [here](https://github.com/ros2/rosidl_runtime_py/blob/master/rosidl_runtime_py/import_message.py#L30).

In ros1, when a module/message type can't be found, a message like

```
ERROR: Cannot load message class for [my_package/MyMessage]. Are your messages built?
```

is shown. Rather than crashing and showing a backtrace, a message like this should be displayed, perhaps something like

```
ERROR: Cannot load message class for [my_package/MyMessage]. Check that the message is built and the workspace is sourced.
```

For reference, the ros1 code is [here](https://github.com/ros/ros_comm/blob/noetic-devel/tools/rostopic/src/rostopic/__init__.py#L1041). The error is printed in the main function after catching the exception, which is why the traceback is not printed.

Perhaps the solution to this is to raise a more informative error message here, and then add some specific handling code in the echo verb.

**Comment by dirk-thomas** [comment]
Please see #558 for a proposed patch to print an error message instead of the traceback.
