### ISSUE TITLE
'ros2 param list' fails when a node isn't spinning

### ISSUE THREAD

**Issue by omertal88** [ros2/ros2cli#764]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 20.04
- Installation type:
  -  Binaries
- Version or commit hash:
  -  Galactic (don't have tag)
- DDS implementation:
  -  CycloneDDS
- Client library (if applicable):
  -  rclcpp

#### Steps to reproduce issue

Create an executable with a node object inside. Don't spin that node.
Then go to CLI and type:
`ros2 param list`. You should get the following error:
```
Exception while calling service of node 'YOUR_NODE_NAME': None
Traceback (most recent call last):
  File "/opt/ros/galactic/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.13.1', 'console_scripts', 'ros2')()
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2cli/cli.py", line 67, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2param/command/param.py", line 39, in main
    return extension.main(args=args)
  File "/opt/ros/galactic/lib/python3.8/site-packages/ros2param/verb/list.py", line 116, in main
    sorted_names = sorted(response.result.names)
AttributeError: 'NoneType' object has no attribute 'result'
```

#### Expected behavior
Should ignore that nodes parameters.
#### Actual behavior
Doesn't handle the None object received by the parameter service.
#### Additional information

----

**Comment by omertal88** [comment]
Just saw this duplicates https://github.com/ros2/ros2cli/issues/645
