### ISSUE TITLE
ros2 param dump UnboundLocalError

### ISSUE THREAD

**Issue by reinzor** [ros2/ros2cli#930]
```
$ ros2 param dump /kalman_filter_map 
Traceback (most recent call last):
  File "/opt/ros/jazzy/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.32.1', 'console_scripts', 'ros2')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2cli/cli.py", line 91, in main
    rc = extension.main(parser=parser, args=args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2param/command/param.py", line 39, in main
    return extension.main(args=args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ros/jazzy/lib/python3.12/site-packages/ros2param/verb/dump.py", line 103, in main
    f"'{node_name.full_name}': {e}", file=sys.stderr)
                                ^
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value
```

**Comment by reinzor** [comment]
@fujitatomoya this issue can be reproduces by the scenario described in https://github.com/cra-ros-pkg/robot_localization/issues/903 . This discussion might be out of scope for this issue but just a friendly FYI as you are the maintainer of this repo :) .
