### ISSUE TITLE
:farmer: TestROS2TopicUseSimTime.test_pub_times failing in Linux Coverage

### ISSUE THREAD

**Issue by Crola1702** [ros2/ros2cli#974]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu Noble
- Installation type:
  - Source
- Version or commit hash:
  - Rolling

#### Steps to reproduce issue
1. Run a build in [nightly_linux_coverage](https://ci.ros2.org/job/nightly_linux_coverage/)
2. See test ros2topic.ros2topic.test.test_use_sim_time.test_use_sim_time fail

#### Additional information

Reference build:
* [nightly_linux_coverage#2511](https://ci.ros2.org/job/nightly_linux_coverage/2511)

Test regression:
* [ros2topic.ros2topic.test.test_use_sim_time.test_use_sim_time](https://ci.ros2.org/job/nightly_linux_coverage/2511/testReport/junit/ros2topic.ros2topic.test/test_use_sim_time/test_use_sim_time/)

Log output:
```
FAIL: test_use_sim_time.TestROS2TopicUseSimTime.test_pub_times
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins-agent/workspace/nightly_linux_coverage/ws/install/launch_testing/lib/python3.12/site-packages/launch_testing/markers.py", line 61, in _wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jenkins-agent/workspace/nightly_linux_coverage/ws/src/ros2/ros2cli/ros2topic/test/test_use_sim_time.py", line 124, in test_pub_times
    assert command.wait_for_shutdown(timeout=5)
AssertionError: assert False
 +  where False = <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x7f2122599580>>(timeout=5)
 +    where <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x7f2122599580>> = <launch_testing.tools.process.ProcessProxy object at 0x7f2122599580>.wait_for_shutdown
```

**Comment by fujitatomoya** [comment]
I cannot reproduce this issue with local environment. @Crola1702 how often this problem has been observed?

**Comment by fujitatomoya** [comment]
@Crola1702 the test failure comes from `ros2cli`, so i just transferred the issue here.
